config/routes.rb
Rails.application.routes.draw do 

  root to: 'application#home'

  resources :users, except: [:show, :destroy]
  resources :bands, only: [:show, :update]
  resources :hosts, only: :show
  resources :tours
  resources :shows
  resources :performances, only: [:index, :show, :update]
  resources :requests, only: [:create, :update]

  get '/band_dashboard', to: 'bands#dashboard'
  get '/host_dashboard', to: 'hosts#dashboard'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/models/host.rb
class Host < User
	has_many :shows
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
	def show
		@host = Host.find(params[:id])
		
	end

	def dashboard
		if current_user and current_user.type == "Host" 
			@host = Host.find(current_user.id)
		  all_shows = current_user.shows
		  respond_to do |format|
		  	format.html{render :dashboard}
		  	format.json{render json: all_shows}
		  end
		else
			redirect_to login_path
		end
	end
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/dashboard.html.erb
<div id="wrapper">
	<!-- Sidebar -->
	<div id="sidebar-wrapper">
		<h1 class="headers"><%= @host.name %></h1>
			<div class="img-rounded">
				<%= image_tag @host.avatar.url(:medium), class: "img-responsive avatar image-resize" %>
			</div>
			<div class="user-bar-pad">
				<p>
					<%= icon('envelope-o') %> <%= @host.email %>
					<br><%= icon('map-marker') %> <%= @host.location %>
				</p>
				<h3><%= link_to "Add Show", new_show_path %></h3>
				<h3><%= link_to "Find Bands", performances_path %></h3>
			</div>
	</div>
	<!-- /#sidebar-wrapper -->
	<!-- Page Content -->
	<div id="page-content-wrapper">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12 dashboard-content">
					<span class="menu-toggle">
						<%= icon('angle-right') %>
					</span>
					<% @host.shows.each do |show| %>
						<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
							<div class="shadowbox">
								<h3 class="headers">
									<%= show.venue %>
								</h3>
								<br>
								<br>
								<div class="card-body">
									<div class="flyer">
										<%= link_to image_tag(show.flyer.url(:medium)), show_path(show), class: "img-responsive" %>
									</div>
									<span><%= show.location %></span>
									<p><%= show.show_date.strftime("%m/%d/%Y") %></p>
									<hr>
									<%= link_to "View details", show_path(show) %><br>
									<%= link_to "Edit", edit_show_path(show) %>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<!-- /#page-content-wrapper -->
</div>

app/views/hosts/show.html.erb
<br>
<div class="container-fluid user">
	<div class="row">
		<div class="col-md-4">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-6 col-xs-6 text-center">
					<h2 class="headers user-headers"><%= @host.name %></h2>
					<div class="user-avatar-wrapper">
						<%= image_tag @host.avatar.url(:medium), class: "img-responsive user-avatar"%>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-6 col-xs-6 info_right">
					<div class="user-info-wrapper">
						<h4><%= icon('envelope-o') %> <%= @host.email %></h4>
						<h4>&emsp;<%= icon('map-marker') %> <%= @host.location %></h4> 
						<% if @host.about == nil and current_user.type == "Host" %>
							<h4><%= icon('music') %> <%= link_to "Please Update", edit_user_path(current_user) %></h4>
						<% else %>
							<h4><%= icon('music') %> <%= @host.about %></h4>
						<% end %>
						</h4>
						<% if current_user.type == "Host" %>
							<h3>
								&emsp;<%= link_to performances_path do %>
									<%= icon('search') %> Find Bands
								<% end %>
							</h3>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-8">
			<% @host.shows.each do |show| %>
				<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
					<div class="shadowbox">
						<h3 class="headers">
							<%= show.venue %>
						</h3>
						<br>
						<br>
						<div class="card-body">
							<div class="flyer">
								<%= image_tag show.flyer.url(:medium) %>
							</div>
							<%= show.show_date.strftime("%m/%d/%Y") %> <br> <span><%= show.location %></span>
							<hr>
							<%= link_to "View details", show_path(show) %><br>
							<% if current_user.type == "Host" %>
								<%= link_to "Edit", edit_show_path(show) %>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>