config/routes.rb
Rails.application.routes.draw do 

  root to: 'application#home'

  resources :users, except: [:show, :destroy]
  resources :bands, only: [:show, :update]
  resources :hosts, only: :show
  resources :tours
  resources :shows
  resources :performances, only: [:index, :show, :update]
  resources :requests, only: [:create, :update]

  get '/band_dashboard', to: 'bands#dashboard'
  get '/host_dashboard', to: 'hosts#dashboard'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://www.weefmgrenada.com/images/na4.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	validates :name, presence: true
	validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  #only validate passoword when signup
	validates	:password, length: {minimum: 6}, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, except: [:index, :new, :create]
  before_action :authorize, except: [:show, :new, :create]

  def new
    @role = ["Host", "Band"]
    @user = User.new
  end

  def create
    #don't let current user create new account
    if !current_user 
      update_user_params = user_params
      city = user_params["location"]
      city.sub!(/, United States/, "")
      update_user_params[:location] = city
      @user = User.new(update_user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Successfully signed up."
        if @user.type == "Host"
          redirect_to host_dashboard_path
        elsif @user.type == "Band"
          redirect_to band_dashboard_path
        end
      else
        flash[:error] = @user.errors.full_messages.join(', ')
        redirect_to signup_path
      end
    elsif current_user and current_user.type == "Host"
      redirect_to host_path(current_user)
    elsif current_user and current_user.type == "Band"
      redirect_to band_path(current_user)
    end
  end

  def edit
    #don't let current user see edit form of other user profile
    #see private method
    unless current_user == @user
      if current_user.type == "Host"
        flash[:notice] = "You can only edit your profile."
        redirect_to host_path(current_user)
      elsif current_user.type == "Band"
        flash[:notice] = "You can only edit your profile."
        redirect_to band_path(current_user)
      end
    end
  end

  def update
    #only current user can update his own account
    if current_user == @user
      if @user.update_attributes(user_params)
        flash[:notice] = "Successfully updated profile."
        if current_user.type == "Host"
          redirect_to host_path(@user)
        elsif current_user.type == "Band"
          redirect_to band_path(@user)
        end
      else
        flash[:error] = @user.errors.full_messages.join(', ')
        redirect_to edit_user_path(@user)
      end
    else 
      #if someone else redirect to signup page
      redirect_to signup_path
    end
  end

  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Successfully delete profile."
      redirect_to root_path
    else
      flash[:error] = "You can't delete someone else's profile." 
      redirect_to user_path(current_user)
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :about, :email, :type, :password, :password_confirmation, :description, :location, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="edit-profile-form">
				<h3 class="text-center form-title">Edit Profile</h3>
				<div class="row">
					<div class="col-xs-10 col-xs-offset-1">
						<%= form_for :user, url: user_path(@user), method: :patch, html: { multipart: true } do |f| %>
							<div class="form-group">
								<%=  f.label :name %>
								<%=  f.text_field :name, class: "form-control", autofocus: true %>
							</div>
							<div class="form-group">
								<%= f.label :avatar %>
								<%= f.file_field :avatar %>
							</div>
							<div class="form-group">
								<%=  f.label :email %>
								<%=  f.email_field :email, class: "form-control" %>
							</div>
							<div class="form-group">
								<%=  f.label :location %>
								<%=  f.text_field :location, class: "form-control" %>
							</div>
							<div class="form-group">
								<%=  f.label :about %>
								<%=  f.text_area :about, rows: 4, class: "form-control" %>
							</div>
							<div class="form-group text-center">
								<%= f.submit "Save changes", class: "btn btn-primary form-control" %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container-fluid signup">
	<div class="row how-it-works">
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
			<div class="tagline-wrapper">
				<%= image_tag "otraband-01.png", class: "logo-info band-signup img-responsive" %>
				<p class="tagline image-labels band-signup">BANDS</p>
			</div>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
			<div class="tagline-wrapper">
				<%= image_tag "otrahosts-01.png", class: "logo-info host-signup img-responsive" %>
				<p class="tagline image-labels host-signup">HOSTS</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12 signup-form-holder">
			<div class="signup-form">
				<h3 class="text-center form-title">Get Started</h3>
				<div class="row">
					<div class="col-xs-10 col-xs-offset-1">
						<%= form_for :user, url: users_path, method: :post, html: { multipart: true } do |f| %>
							<div class="form-group">
								<%=  f.label :name %>
								<%=  f.text_field :name, class: "form-control", required: true %>
							</div>
							<div class="form-group">
								<%=  f.label :email %>
								<%=  f.email_field :email, class: "form-control", required: true %>
							</div>
							<div class="form-group">
								<%=  f.label :location %>
								<%=  f.text_field :location, class: "form-control city_stops", required: true %>
							</div>
							<div class="form-group">
								<%=  f.label :type, "Band/Host" %>
								<%=  f.collection_select :type, @role, :to_s, :to_s, {prompt: "Are you are band or host?"}, class: "form-control", required: true %>
							</div>
							<div class="form-group">
								<%=  f.label :password %>
								<%=  f.password_field :password, class: "form-control", required: true %>
							</div>
							<div class="form-group">
								<%=  f.label :password_confirmation %>
								<%=  f.password_field :password_confirmation, class: "form-control", required: true %>
							</div>
							<div class="form-group text-center">
								<%= f.submit "Sign Up", class: "btn btn-primary form-control" %>
							</div>
						<% end %>
						<p class="text-center login-signup-footer">Already a member? <%= link_to "Click Here", login_path %> to login.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>