config/routes.rb
Rails.application.routes.draw do 

  root to: 'application#home'

  resources :users, except: [:show, :destroy]
  resources :bands, only: [:show, :update]
  resources :hosts, only: :show
  resources :tours
  resources :shows
  resources :performances, only: [:index, :show, :update]
  resources :requests, only: [:create, :update]

  get '/band_dashboard', to: 'bands#dashboard'
  get '/host_dashboard', to: 'hosts#dashboard'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/models/band.rb
class Band < User
	has_many :tours
	has_many :performances
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	before_action :band_performances

	def show
		if current_user and current_user.type == "Band"
			@band = Band.find(params[:id])
		else 
			redirect_to login_path
		end
	end

	def dashboard
		if current_user and current_user.type == "Band" 
		  respond_to do |format|
		  	format.html{render :dashboard}
		  	format.json{render json: @all_performances}
		  end
		else
			redirect_to login_path
		end
	end
	private
	def band_performances
		@pending_performances = []
		current_user.performances.each do |performance|
			pending = performance.requests.where(status: "pending")
			if pending.any?
				@pending_performances << pending[0].performance
			end
		end
		@band = Band.find(current_user.id)
	  @all_performances = current_user.performances.group_by {|performance| performance.tour_id}.to_a
	  @all_performances.sort!
	end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/dashboard.html.erb
<div id="wrapper">
	<!-- Sidebar -->
	<div id="sidebar-wrapper">
		<h1 class="headers"><%= @band.name %></h1>
			<div class="img-rounded">
				<%= image_tag @band.avatar.url(:medium), class: "img-responsive avatar image-resize" %>
			</div>
			<div class="user-bar-pad">
				<p>
					<%= icon('envelope-o') %> <%= @band.email %>
					<br><%= icon('map-marker') %> <%= @band.location %>
				</p>
				<h3><%= link_to "Add Tour", new_tour_path %></h3>
				<h3><%= link_to "Find Venue", shows_path %></h3>
			</div>
	</div>
	<!-- /#sidebar-wrapper -->
	<!-- Page Content -->
	<div id="page-content-wrapper">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12 dashboard-content">
					<span class="menu-toggle">
						<%= icon('angle-right') %>
					</span>
					<% @band.tours.each do |tour| %>
						<div class="row">
							<div class="col-lg-12">
								<div class="shadowbox">
									<h3 class="map-headers"><%= tour.name %><span class="glyphicon glyphicon-globe pull-right view-map"></span></h3>
									<div id="map<%= @band.tours.index(tour) %>" class="map">
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
								<div class="shadowbox">
									<h3 class="headers">SCHEDULED SHOWS</h3>
									<br>
									<br>
									<div class="card-body">
										<% tour.performances.where(status: 'scheduled').each do |perf| %>
											<% if @pending_performances.include?(perf) == false %>
												<%= link_to perf.performance_date.strftime("%m/%d/%Y"), performance_path(perf) %> <br> <span><%= link_to perf.location, performance_path(perf) %></span>
												<hr>
											<% end %>
										<% end %>
									</div>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
								<div class="shadowbox">
									<h3 class="headers">PENDING SHOWS</h3>
									<br>
									<br>
									<div class="card-body">
										<% tour.performances.where(status: 'scheduled').each do |perf| %>
											<% if @pending_performances.any? %>
												<% if @pending_performances.include?(perf) %>
													<%= link_to perf.performance_date.strftime("%m/%d/%Y"), performance_path(perf) %> <br> <span><%= link_to perf.location, performance_path(perf) %></span>
													<hr>
												<% end %>
											<% end %>
										<% end %>
									</div>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
								<div class="shadowbox">
									<h3 class="headers">CONFIRMED SHOWS</h3>
									<br>
									<br>
									<div class="card-body">
										<% tour.performances.where(status: 'confirmed').each do |perf| %>
										<%= link_to perf.performance_date.strftime("%m/%d/%Y"), performance_path(perf) %> <br> 
										<span><%= link_to perf.location, performance_path(perf) %></span>
										<hr>
										<% end %>
									</div>
								</div>
							</div>
						</div>
						<hr>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<!-- /#page-content-wrapper -->
</div>

app/views/bands/show.html.erb
<br>
<div class="container-fluid user">
	<div class="row">
		<div class="col-md-4">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-6 col-xs-6 text-center">
					<h2 class="headers user-headers"><%= @band.name %></h2>
					<div class="user-avatar-wrapper">
						<%= image_tag @band.avatar.url(:medium), class: "img-responsive user-avatar"%>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-6 col-xs-6 info_right">
					<div class="user-info-wrapper">
						<h4><%= icon('envelope-o') %> <%= @band.email %></h4>
						<h4>&emsp;<%= icon('map-marker') %> <%= @band.location %></h4> 
						<% if @band.about == nil and current_user.type == "Band" %>
							<h4><%= icon('music') %> <%= link_to "Please Update", edit_user_path(current_user) %></h4>
						<% else %>
							<h4><%= icon('music') %> <%= @band.about %></h4>
						<% end %>
						</h4>
						<% if current_user.type == "Band" %>
							<h3>
								&emsp;<%= link_to shows_path do %>
									<%= icon('search') %> Find Venues
								<% end %>
							</h3>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-8">
			<div class="dashboard-content">
				<% @band.tours.each do |tour| %>
					<div class="row tours">
						<div class="col-md-12">
							<div class="row">
								<div class="col-md-12">
									<div class="shadowbox tour-name">
										<h3 class="headers"><span class="glyphicon glyphicon-globe"></span> <%= tour.name %></h3>
									</div>
								</div>
							</div>
							<div class="row performance-tags">
								<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
									<div class="shadowbox">
										<h3 class="headers">SCHEDULED SHOWS</h3>
										<br>
										<br>
										<div class="card-body">
											<% tour.performances.where(status: 'scheduled').each do |perf| %>
												<% if @pending_performances.include?(perf) == false %>
													<%= perf.performance_date.strftime("%m/%d/%Y") %> <br> <span><%= perf.location %></span>
													<hr>
												<% end %>
											<% end %>
										</div>
									</div>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
									<div class="shadowbox">
										<h3 class="headers">PENDING SHOWS</h3>
										<br>
										<br>
										<div class="card-body">
											<% tour.performances.where(status: 'scheduled').each do |perf| %>
												<% if @pending_performances.any? %>
													<% if @pending_performances.include?(perf) %>
														<%= perf.performance_date.strftime("%m/%d/%Y") %> <br> <span><%= perf.location %></span>
														<hr>
													<% end %>
												<% end %>
											<% end %>
										</div>
									</div>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
									<div class="shadowbox">
										<h3 class="headers">CONFIRMED SHOWS</h3>
										<br>
										<br>
										<div class="card-body">
											<% tour.performances.where(status: 'confirmed').each do |perf| %>
											<%= link_to perf.performance_date.strftime("%m/%d/%Y"), performance_path(perf) %> <br> 
											<span><%= perf.location %></span>
											<hr>
											<% end %>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<hr>
				<% end %>
			</div>
		</div>
	</div>
</div>