config/routes.rb
Rails.application.routes.draw do 

  root to: 'application#home'

  resources :users, except: [:show, :destroy]
  resources :bands, only: [:show, :update]
  resources :hosts, only: :show
  resources :tours
  resources :shows
  resources :performances, only: [:index, :show, :update]
  resources :requests, only: [:create, :update]

  get '/band_dashboard', to: 'bands#dashboard'
  get '/host_dashboard', to: 'hosts#dashboard'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OTRA</title>
  <meta name="viewport" content="width=400, initial-scale=1">
  <meta name="viewport" content="width=300, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCJ7P4CWIAkLESUlm41nz7ZfacCFdiN7bc&libraries=places&region=us">
  </script>

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="//cdn.jsdelivr.net/jquery.geocomplete/1.6.4/jquery.geocomplete.min.js"></script>

</head>
<body>
	<!-- navbar -->
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	    	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
	      <%= link_to "Otra", root_path, class: "navbar-brand" %>
	    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="navbar-collapse collapse" id="bs-navbar">
		    <ul class="nav navbar-nav navbar-right">
		      <% if current_user && current_user.type == "Band" %>
		      <li><%= link_to "Dashboard", band_dashboard_path, class: "nav-links" %></li>
		      <li><%= link_to "Add Tour", new_tour_path, class: "nav-links" %></li>
		      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %> <span class="caret"></span></a>
		        <ul class="dropdown-menu">
		          <li><%= link_to "Band Profile", band_path(current_user), class: "nav-links" %></li>
		          <li><%= link_to "Edit Profile", edit_user_path(current_user), class: "nav-links" %></a></li>
		          <li><%= link_to "Logout", logout_path, class: "nav-links" %></li>
		        </ul>
		      </li>
		      <% elsif current_user && current_user.type == "Host" %>
						<li><%= link_to "Dashboard", host_dashboard_path, class: "nav-links" %></li>
						<li><%= link_to "Add Show", new_show_path, class: "nav-links" %></li>
						<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %> <span class="caret"></span></a>
						  <ul class="dropdown-menu">
						    <li><%= link_to "Your Profile", host_path(current_user), class: "nav-links" %></li>
						    <li><%= link_to "Edit Profile", edit_user_path(current_user), class: "nav-links" %></a></li>
						    <li><%= link_to "Logout", logout_path, class: "nav-links" %></li>
						  </ul>
						</li>
		      <% else %>
		      <li><%= link_to "Signup", signup_path, class: "nav-links" %></li>
		      <li><%= link_to "Login", login_path, class: "nav-links" %></li>
		      <% end %>
		    </ul>
		  </div>
	  </div>
	</nav>
	<!-- error message -->
	<% flash.each do |name, msg| %>
	  <div class="alert <%= name == 'error' ? 'alert-danger' : 'alert-info' %>">
	    <div class="container">
	      <%= msg %>
	    </div>
	  </div>
	<% end %>
	<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12 otra-holder">
			<div class="welcome text-center"><br><br><br>
				<%= image_tag "otra-01.png", class: "logo" %>
				<p class="otra">On the road again?</p>
				<br>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-10 col-lg-offset-1 text-center">
			<div class="info text-center">
				<hr>
				<div class="info-header">
					<p>LET US DO SOME HEAVY LIFTING</p>
				</div>
				<hr>
				<h3>Otra provides a platform for touring bands and independent show hosts to connect efficiently and painlessly</h3>
				<p><a href="#how-it-work" class="down-arrow"><%= icon('angle-down') %></a></p>
			</div>
		</div>
	</div>

	<section id="how-it-work">
		<div class="row how-it-works">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
				<div class="tagline-wrapper">
					<%= image_tag "otraband-01.png", class: "logo-info img-responsive" %>
					<hr class="divider-line">
					<%= link_to "BANDS", signup_path, class: "tagline image-labels band-signup" %>
					<hr class="divider-line">
					<% if !current_user %>
						<h4><strong><%= link_to "Signup", signup_path, class: "band-signup" %></strong> as a band and get started by creating a tour route and connecting with hosts!</h4>
					<% end %>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-center">
				<div class="tagline-wrapper">
					<%= image_tag "otrahosts-01.png", class: "logo-info img-responsive" %>
					<hr class="divider-line">
					<%= link_to "HOSTS", signup_path, class: "tagline image-labels host-signup" %>
					<hr class="divider-line">
					<% if !current_user %>
						<h4><strong><%= link_to "Signup", signup_path, class: "host-signup" %></strong> as a host and get started by creating some shows and connecting with bands!</h4>
					<% end %>
				</div>
			</div>
		</div>
	</section>
</div>